feat: action test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,5 +1,5 @@
 name: CodeFundi Build Diagnosis AI
-description: Automatically capture and diagnose errors in your Github Action logs.
+description: Automatically capture and diagnose errors in your GitHub Action logs.
 author: CodeFundi
 branding:
   icon: zap
@@ -16,7 +16,7 @@ inputs:
     required: true
     default: ''
   silent:
-    description: Runs Code Fundi in silent mode if true.
+    description: Runs CodeFundi in silent mode if true.
     required: false
     default: 'false'
     type: boolean
@@ -31,7 +31,7 @@ runs:
       id: run-command
       shell: bash
       run: |
-        set +e  # Temporarily disable exit on error
+        set +e
         
         # Run the npm command
         ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
@@ -45,9 +45,16 @@ runs:
             SILENT_FLAG="-s"
           fi
 
+          # Run CodeFundi diagnosis and wait for it to complete
           npx @codefundi/cli --key="${{ inputs.key }}" --diagnose "$ERROR_LOG" $SILENT_FLAG
+          WAIT_CODE=$?
+          if [ $WAIT_CODE -ne 0 ]; then
+            echo "❗ Diagnosis command failed with exit code $WAIT_CODE."
+          else
+            echo "🔍 Diagnosis completed successfully."
+          fi
         else
           echo "✅ Command ran successfully."
         fi
 
-        set -e  # Re-enable exit on error
+        set -e
