feat: action test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,29 +28,47 @@ runs:
       with:
         node-version: '18'
 
-    - name: Run npm command and capture errors
+    - name: Set up NPM
+      id: run-npm
+      shell: bash
+      run: npm install npm -g        
+        
+    - name: Run npm command and handle errors
       id: run-command
+      shell: bash
       run: |
         set +e
+        
+        # Run the npm command
         ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
-        echo "$ERROR_LOG" > error_log.txt
-        echo "::set-output name=exit-code::$?"
-        set -e
+        EXIT_CODE=$?
+        
+        if [ $EXIT_CODE -ne 0 ]; then
+          echo "🚫 Command failed with exit code $EXIT_CODE. Running diagnosis..."
+          
+          SILENT_FLAG=""
+          if [ "${{ inputs.silent }}" = "true" ]; then
+            SILENT_FLAG="-s"
+          fi
 
-    - name: Check if the command failed
-      id: check-failure
-      run: |
-        if [ "${{ steps.run-command.outputs.exit-code }}" -ne 0 ]; then
-          echo "true" > failed.txt
+          # Output the error log for debugging
+          echo "Captured error log:"
+          echo "$ERROR_LOG"
+
+          # Run CodeFundi diagnosis and log its output for debugging
+          echo "Running CodeFundi diagnosis..."
+          DIAGNOSIS_OUTPUT=$(npx --yes @codefundi/cli --key="${{ inputs.key }}" --diagnose "$ERROR_LOG" $SILENT_FLAG 2>&1)
+          DIAGNOSIS_EXIT_CODE=$?
+
+          echo "$DIAGNOSIS_OUTPUT"
+
+          if [ $DIAGNOSIS_EXIT_CODE -ne 0 ]; then
+            echo "❗ Diagnosis command failed with exit code $DIAGNOSIS_EXIT_CODE."
+          else
+            echo "🔍 Diagnosis completed successfully."
+          fi
         else
-          echo "false" > failed.txt
-      continue-on-error: true
-
-    - name: Run CodeFundi Diagnosis if command failed
-      if: ${{ steps.check-failure.outputs.failed == 'true' }}
-      run: |
-        SILENT_FLAG=""
-        if [ "${{ inputs.silent }}" = "true" ]; then
-          SILENT_FLAG="-s"
+          echo "✅ Command ran successfully."
         fi
-        npx --yes @codefundi/cli --key="${{ inputs.key }}" --diagnose "$(cat error_log.txt)" $SILENT_FLAG
+
+        set -e
